# Generated by Django 3.1.5 on 2021-01-17 16:21

from django.db import migrations


def capitalize(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    for product in Product.objects.all():
        product.name = product.name.capitalize()
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_productimage_thumbnail"),
    ]

    operations = [
        migrations.RunPython(capitalize, migrations.RunPython.noop),
    ]
